//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace API.FinService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FinserviceSoap", Namespace="http://tempuri.org/")]
    public partial class Finservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AuthenOperationCompleted;
        
        private System.Threading.SendOrPostCallback XmlUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback XmlAuthenOperationCompleted;
        
        private System.Threading.SendOrPostCallback blankNodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback blankStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback permissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStudentUIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback infoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Finservice() {
            this.Url = global::API.Properties.Settings.Default.API_FinService_Finservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AuthenCompletedEventHandler AuthenCompleted;
        
        /// <remarks/>
        public event XmlUserInfoCompletedEventHandler XmlUserInfoCompleted;
        
        /// <remarks/>
        public event XmlAuthenCompletedEventHandler XmlAuthenCompleted;
        
        /// <remarks/>
        public event blankNodeCompletedEventHandler blankNodeCompleted;
        
        /// <remarks/>
        public event blankStringCompletedEventHandler blankStringCompleted;
        
        /// <remarks/>
        public event permissionCompletedEventHandler permissionCompleted;
        
        /// <remarks/>
        public event getStudentUIDCompletedEventHandler getStudentUIDCompleted;
        
        /// <remarks/>
        public event infoCompletedEventHandler infoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Authen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Authen(string _username, string _password, string _usertype) {
            object[] results = this.Invoke("Authen", new object[] {
                        _username,
                        _password,
                        _usertype});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenAsync(string _username, string _password, string _usertype) {
            this.AuthenAsync(_username, _password, _usertype, null);
        }
        
        /// <remarks/>
        public void AuthenAsync(string _username, string _password, string _usertype, object userState) {
            if ((this.AuthenOperationCompleted == null)) {
                this.AuthenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenOperationCompleted);
            }
            this.InvokeAsync("Authen", new object[] {
                        _username,
                        _password,
                        _usertype}, this.AuthenOperationCompleted, userState);
        }
        
        private void OnAuthenOperationCompleted(object arg) {
            if ((this.AuthenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenCompleted(this, new AuthenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XmlUserInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string XmlUserInfo(string _username, string type) {
            object[] results = this.Invoke("XmlUserInfo", new object[] {
                        _username,
                        type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void XmlUserInfoAsync(string _username, string type) {
            this.XmlUserInfoAsync(_username, type, null);
        }
        
        /// <remarks/>
        public void XmlUserInfoAsync(string _username, string type, object userState) {
            if ((this.XmlUserInfoOperationCompleted == null)) {
                this.XmlUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXmlUserInfoOperationCompleted);
            }
            this.InvokeAsync("XmlUserInfo", new object[] {
                        _username,
                        type}, this.XmlUserInfoOperationCompleted, userState);
        }
        
        private void OnXmlUserInfoOperationCompleted(object arg) {
            if ((this.XmlUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XmlUserInfoCompleted(this, new XmlUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XmlAuthen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string XmlAuthen(string _username, string _password, string type) {
            object[] results = this.Invoke("XmlAuthen", new object[] {
                        _username,
                        _password,
                        type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void XmlAuthenAsync(string _username, string _password, string type) {
            this.XmlAuthenAsync(_username, _password, type, null);
        }
        
        /// <remarks/>
        public void XmlAuthenAsync(string _username, string _password, string type, object userState) {
            if ((this.XmlAuthenOperationCompleted == null)) {
                this.XmlAuthenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXmlAuthenOperationCompleted);
            }
            this.InvokeAsync("XmlAuthen", new object[] {
                        _username,
                        _password,
                        type}, this.XmlAuthenOperationCompleted, userState);
        }
        
        private void OnXmlAuthenOperationCompleted(object arg) {
            if ((this.XmlAuthenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XmlAuthenCompleted(this, new XmlAuthenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/blankNode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode blankNode(string _username, string _password) {
            object[] results = this.Invoke("blankNode", new object[] {
                        _username,
                        _password});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void blankNodeAsync(string _username, string _password) {
            this.blankNodeAsync(_username, _password, null);
        }
        
        /// <remarks/>
        public void blankNodeAsync(string _username, string _password, object userState) {
            if ((this.blankNodeOperationCompleted == null)) {
                this.blankNodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnblankNodeOperationCompleted);
            }
            this.InvokeAsync("blankNode", new object[] {
                        _username,
                        _password}, this.blankNodeOperationCompleted, userState);
        }
        
        private void OnblankNodeOperationCompleted(object arg) {
            if ((this.blankNodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.blankNodeCompleted(this, new blankNodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/blankString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string blankString() {
            object[] results = this.Invoke("blankString", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void blankStringAsync() {
            this.blankStringAsync(null);
        }
        
        /// <remarks/>
        public void blankStringAsync(object userState) {
            if ((this.blankStringOperationCompleted == null)) {
                this.blankStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnblankStringOperationCompleted);
            }
            this.InvokeAsync("blankString", new object[0], this.blankStringOperationCompleted, userState);
        }
        
        private void OnblankStringOperationCompleted(object arg) {
            if ((this.blankStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.blankStringCompleted(this, new blankStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/permission", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool permission(string _username, string _menuId) {
            object[] results = this.Invoke("permission", new object[] {
                        _username,
                        _menuId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void permissionAsync(string _username, string _menuId) {
            this.permissionAsync(_username, _menuId, null);
        }
        
        /// <remarks/>
        public void permissionAsync(string _username, string _menuId, object userState) {
            if ((this.permissionOperationCompleted == null)) {
                this.permissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpermissionOperationCompleted);
            }
            this.InvokeAsync("permission", new object[] {
                        _username,
                        _menuId}, this.permissionOperationCompleted, userState);
        }
        
        private void OnpermissionOperationCompleted(object arg) {
            if ((this.permissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.permissionCompleted(this, new permissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getStudentUID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getStudentUID(string _username) {
            object[] results = this.Invoke("getStudentUID", new object[] {
                        _username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getStudentUIDAsync(string _username) {
            this.getStudentUIDAsync(_username, null);
        }
        
        /// <remarks/>
        public void getStudentUIDAsync(string _username, object userState) {
            if ((this.getStudentUIDOperationCompleted == null)) {
                this.getStudentUIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStudentUIDOperationCompleted);
            }
            this.InvokeAsync("getStudentUID", new object[] {
                        _username}, this.getStudentUIDOperationCompleted, userState);
        }
        
        private void OngetStudentUIDOperationCompleted(object arg) {
            if ((this.getStudentUIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStudentUIDCompleted(this, new getStudentUIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/info", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet info(string _string) {
            object[] results = this.Invoke("info", new object[] {
                        _string});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void infoAsync(string _string) {
            this.infoAsync(_string, null);
        }
        
        /// <remarks/>
        public void infoAsync(string _string, object userState) {
            if ((this.infoOperationCompleted == null)) {
                this.infoOperationCompleted = new System.Threading.SendOrPostCallback(this.OninfoOperationCompleted);
            }
            this.InvokeAsync("info", new object[] {
                        _string}, this.infoOperationCompleted, userState);
        }
        
        private void OninfoOperationCompleted(object arg) {
            if ((this.infoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.infoCompleted(this, new infoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void AuthenCompletedEventHandler(object sender, AuthenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void XmlUserInfoCompletedEventHandler(object sender, XmlUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XmlUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XmlUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void XmlAuthenCompletedEventHandler(object sender, XmlAuthenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XmlAuthenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XmlAuthenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void blankNodeCompletedEventHandler(object sender, blankNodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class blankNodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal blankNodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void blankStringCompletedEventHandler(object sender, blankStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class blankStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal blankStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void permissionCompletedEventHandler(object sender, permissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class permissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal permissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getStudentUIDCompletedEventHandler(object sender, getStudentUIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStudentUIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStudentUIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void infoCompletedEventHandler(object sender, infoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class infoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal infoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591